### ISSUE TITLE
原来 Guanrenfu 还活着（手动滑稽）

### ISSUE THREAD

**Issue by lideming** [K-Guan/Learn#1]

**Comment by K-Guan** [comment]
_Are you spamming the "Issues" page of my project? Who are you by the way?_

**Comment by lideming** [comment]
@K-Guan 我就是贴吧头像是火狐的那家伙啊:joy:

**Comment by K-Guan** [comment]
啊……有点印象了。Linux吧小吧咯？话说吧里情况如何？

**Comment by lideming** [comment]
@K-Guan 自己去看一下<del>顺便水一贴</del>不就知道了，
话说我的头像的PSD和高清版找不到了，只有从贴吧截的渣画质 :new_moon_with_face:

**Comment by K-Guan** [comment]
@lideming 刚看了眼，还和以前差不多。水一帖就免了，我的帐号早已被我从我的 LastPass 里删掉了。贴吧呀……没意思。
